database posthog {
    table events {
         
    }
    
    table sharded_events {
    
        column uuid {
            type = "UUID"
        }
        
        engine "merge_tree" {
        }
    }
}
