name: production
nodes:
  - host: clickhouse-01a
    port: 9000
    shard: 1
    replica: 1
  - host: clickhouse-01b
    port: 9000
    shard: 1
    replica: 2
  - host: clickhouse-02a
    port: 9000
    shard: 2
    replica: 1
  - host: clickhouse-02b
    port: 9000
    shard: 2
    replica: 2
